name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 82.25.105.110
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          fingerprint: 5d:38:4c:67:77:e8:76:8b:ff:b6:94:3a:a8:de:19:01
          script: bash /opt/sites/filim/deploy.sh
          command_timeout: 12m
